### PR TITLE
Fix existing tests & turn transition computation

### PR DESCRIPTION
**Pull request by jordanreedie**
## Description
All tests now run & pass consistently. Utterances that are passed to the turn transition computation function are now sorted beforehand, which prevents out-of-order utterances from messing with the calculation. Removed 'mergeHook' from the list of before hooks for utterances. This was an old hook that I don't believe worked, and if it *did* work I don't think we would have wanted it in the pipeline.

Individual Changes are below:
 - increasing default timeout makes tests run more consistently
  - fix broken utterance test
  - fix transition functionality so that turns test isn't broken
  - remove mergeHook
  - rename very misleading / confusing variables in getTurnTransitions
  - only use the global socket instead of a bunch of unique sockets
    for each test
  - dropDatabase no longer leaves a mongoclient open every time
    it's called
  - stop all jobs on cleanup after tests run
  - make sure mongoose connection closes on cleanup

## Motivation and context
We've got all these existing tests but never bother running them because they've been broken for a while. Now they work!

## How has this been tested?
I ran the tests a bunch of times and they passed every time

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ My change requires a change to the documentation and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by ebporter** [comment]
Wow!! Nicely done.

**Comment by adonahue** [comment]
Whoo Hoo! Awesome @jordanreedie !

**Comment by mlippert** [comment]
I'm going to push the commit I made addressing things in my review above so you @jordanreedie can see them.

**Comment by mlippert** [comment]
I had one other question:
I see the change to use the global socket in the tests, is that because the tests are already using the global app services?

**Comment by jordanreedie** [comment]
>     * If we're getting rid of the mergeHook, I think we should remove the `mergeHook.js` file as well. Do you agree?
Yeah that sounds right to me
> 
>     * there are a couple of new lint errors, I've already made the changes to get rid of them.
Thanks :)
>     *I added a comment in global-before.js that explains that dropDatabase is creating a new  different connection to the mongodb in order to drop the database, and is then making sure that new connection is closed. It is not touching the existing mongoose connection to mongodb that was setup in services/index.js. It took me a long time to figure out that is what was going on, so I thought it was worth adding a comment, assuming I'm correct.

Yeah, that took me a while to figure out also so I should have for sure dropped a comment in there :sweat_smile: 

> I see the change to use the global socket in the tests, is that because the tests are already using the global app services?

Yeah, that and some of the tests were already using the global socket anyway, so I figured I might as well convert them all - less potential loose ends to worry about

**Comment by mlippert** [comment]
squashed minor changes into main commit for merge

**Comment by mlippert** [comment]
**Release** [0.4.0-dev.14](https://github.com/rifflearning/riff-server/releases/tag/0.4.0-dev.14)

**Pull request merged**
