### PR TITLE
encrypt PII at rest

### PR DESCRIPTION
**Pull request by jordanreedie**
encrypt the name and email fields in participant model at rest

## Description
Encrypt users' PII per our requirements. Note that redeploying to existing environments with this will be tricky due to a mix of encrypted / unencrypted data

Therefore there are also 2 "scripts", one to encrypt the existing data in the database, and one
to decrypt it.

The encrypt script can be invoked in a running riffdata container like this:
```
docker exec <riffdata-container-name> node src/scripts/encrypt-participants.js
```
The script will use the same configuration to connect to the database as the server running in
that container, and will also get the `database.value_encryption_key` from that config.

## Motivation and context
Gotta meet client requirements. We used to encrypt some stuff, so I fished most of that code out of the git history and made some changes to it.

## How has this been tested?
Tested locally - with a fresh database, I started a meeting and then inspected both the name and email of the participants in the database. Also, confirmed that they are decrypted when the fields are accessed through feathers (they show up properly in the dashboard)

Also tested on dev.riffplatform.com

## Types of changes

- ✅ New feature (non-breaking change which adds functionality)
- ✅ Breaking change (fix or feature that would cause existing functionality to change) (sort of)

## Checklist:

- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ My change requires a change to the documentation and I have updated it accordingly.

### CODE REVIEW

**Comment by jordanreedie** [comment]
[Encrypt PII in Riff Database](https://trello.com/c/a2OdOqls/289-encrypt-pii-in-riff-database)

**Comment by mlippert** [comment]
@jordanreedie I've just rebased to the head of develop, and added a commit which fixed the style errors and also uses the key that is now found in the config file. You should look over the changes in that commit, AND test this. Then comment here if all is good.

Keep in mind that the latest code in the riff-server develop branch needs the latest changes in the riff-docker master branch for running a riff-server container that will work.

**Comment by jordanreedie** [comment]
tested this locally, seems to be all good

**Comment by mlippert** [comment]
force pushed after squashing commits to have meaningful changes in each commit

**Pull request merged**
